from collections import defaultdict
import re
import urllib

dict_of_journals = {

'PROCEEDINGSOFTHENATIONALACADEMYOFSCIENCES' : 'PROCEEDINGS OF THE NATIONAL ACADEMY OF SCIENCES OF THE UNITED STATES',
'PROCNATLACADSCIUSA' : 'PROCEEDINGS OF THE NATIONAL ACADEMY OF SCIENCES OF THE UNITED STATES',
'PROCEEDINGSOFTHENATIONALACADEMYOFSCIENCESOFTHEUNITEDSTATESOFAMERICA' : 'PROCEEDINGS OF THE NATIONAL ACADEMY OF SCIENCES OF THE UNITED STATES',
'PNAS' : 'PROCEEDINGS OF THE NATIONAL ACADEMY OF SCIENCES OF THE UNITED STATES',
'PNASEARLYEDITION' : 'PROCEEDINGS OF THE NATIONAL ACADEMY OF SCIENCES OF THE UNITED STATES',
'PNASPROCEEDINGSOFTHENATIONALACADEMYOFSCIENCESOFTHEUNITEDSTATESOFAMERICA' : 'PROCEEDINGS OF THE NATIONAL ACADEMY OF SCIENCES OF THE UNITED STATES',
'PNASPROCEEDINGSOFTHENATIONALACADEMYOFTHESCIENCES' : 'PROCEEDINGS OF THE NATIONAL ACADEMY OF SCIENCES OF THE UNITED STATES',
'PNASUSA' : 'PROCEEDINGS OF THE NATIONAL ACADEMY OF SCIENCES OF THE UNITED STATES',
'PNATLACADSCIUSA' : 'PROCEEDINGS OF THE NATIONAL ACADEMY OF SCIENCES OF THE UNITED STATES',
'PROCEEDINGSOFTHENATIONACADEMIESOFSCIENCES' : 'PROCEEDINGS OF THE NATIONAL ACADEMY OF SCIENCES OF THE UNITED STATES',
'PROCEEDINGSOFTHENATIONALACADEMYOFSCIENCE' : 'PROCEEDINGS OF THE NATIONAL ACADEMY OF SCIENCES OF THE UNITED STATES',
'ROCEEDINGSOFTHENATIONALACADEMYOFSCIENCEOFTHEUNITEDSATESOFAMERICA' : 'PROCEEDINGS OF THE NATIONAL ACADEMY OF SCIENCES OF THE UNITED STATES',
'PROCEEDINGSOFTHENATIONALACADEMYOFSCIENCEOFTHEUNITEDSTATESOFAMERICA' : 'PROCEEDINGS OF THE NATIONAL ACADEMY OF SCIENCES OF THE UNITED STATES',
'PROCEEDINGSOFTHENATIONALACADEMYOFSCIENCEOFTHEUSA' : 'PROCEEDINGS OF THE NATIONAL ACADEMY OF SCIENCES OF THE UNITED STATES',
'PROCEEDINGSOFTHENATIONALACADEMYOFSCIENCES' : 'PROCEEDINGS OF THE NATIONAL ACADEMY OF SCIENCES OF THE UNITED STATES',
'PROCEEDINGSOFTHENATIONALACADEMYOFSCIENCESOFTHEUNITEDSSTATESOFAMERICA' : 'PROCEEDINGS OF THE NATIONAL ACADEMY OF SCIENCES OF THE UNITED STATES',
'PROCEEDINGSOFTHENATIONALACADEMYOFSCIENCESOFTHEUNITEDSTATES' : 'PROCEEDINGS OF THE NATIONAL ACADEMY OF SCIENCES OF THE UNITED STATES',
'PROCEEDINGSOFTHENATIONALACADEMYOFSCIENCESOFTHEUNITEDSTATESOFAMERICA' : 'PROCEEDINGS OF THE NATIONAL ACADEMY OF SCIENCES OF THE UNITED STATES',
'PROCEEDINGSOFTHENATIONALACADEMYOFSCIENCESOFTHEUNITEDSTATESOFAMERICAJOURNAL' : 'PROCEEDINGS OF THE NATIONAL ACADEMY OF SCIENCES OF THE UNITED STATES',
'PROCEEDINGSOFTHENATIONALACADEMYOFSCIENCESOFTHEUNITEDSTATESOFAMERICAPNAS' : 'PROCEEDINGS OF THE NATIONAL ACADEMY OF SCIENCES OF THE UNITED STATES',
'PROCEEDINGSOFTHENATIONALACADEMYOFSCIENCESOFTHEUNITEDSTATESOFAMERICAPNASPROCEEDINGSOFTHENATIONALACADEMYOFSCIENCES' : 'PROCEEDINGS OF THE NATIONAL ACADEMY OF SCIENCES OF THE UNITED STATES',
'PROCEEDINGSOFTHENATIONALACADEMYOFSCIENCESOFTHEUSA' : 'PROCEEDINGS OF THE NATIONAL ACADEMY OF SCIENCES OF THE UNITED STATES',
'PROCEEDINGSOFTHENATIONALACADEMYOFSCIENCESUSA' : 'PROCEEDINGS OF THE NATIONAL ACADEMY OF SCIENCES OF THE UNITED STATES',
'PROCEEDINGSOFTHENATIONALACADEMYOFSCIENCEUSA' : 'PROCEEDINGS OF THE NATIONAL ACADEMY OF SCIENCES OF THE UNITED STATES',
'PROCEEDINGSOFTHENATIONALACADEMYOFTHESCIENCESOFTHEUNITEDSTATESOFAMERICA' : 'PROCEEDINGS OF THE NATIONAL ACADEMY OF SCIENCES OF THE UNITED STATES',

'JBIOLCHEM' : 'THE JOURNAL OF BIOLOGICAL CHEMISTRY',
'THEJOURNALOFBIOLOGICALCHEMISTRY' : 'THE JOURNAL OF BIOLOGICAL CHEMISTRY',
'JOURNALOFBIOLOGICALCHEMISTRY' : 'THE JOURNAL OF BIOLOGICAL CHEMISTRY',
'JOURNALOFBIOCHEMISTRY' : 'THE JOURNAL OF BIOLOGICAL CHEMISTRY',

'THEJOURNALOFTHEAMERICANCHEMICALSOCIETY' : 'JOURNAL OF THE AMERICAN CHEMICAL SOCIETY',
'JOURNALOFTHEAMERICANCHEMICALSOCIETY' : 'JOURNAL OF THE AMERICAN CHEMICAL SOCIETY',
'JAMCHEMSOC': 'JOURNAL OF THE AMERICAN CHEMICAL SOCIETY',

'NENGLJMED' : 'THE NEW ENGLAND JOURNAL OF MEDICINE',
'NEWENGLANDJOURNALOFMEDICINE' : 'THE NEW ENGLAND JOURNAL OF MEDICINE',
'THENEWENGLANDJOURNALOFMEDICINE' : 'THE NEW ENGLAND JOURNAL OF MEDICINE',

'BMJBRITISHMEDICALJOURNAL' : 'BRITISH MEDICAL JOURNAL',
'BMJ' : 'BRITISH MEDICAL JOURNAL',
'BRITISHMEDICALJOURNAL' : 'BRITISH MEDICAL JOURNAL',
'THEBRITISHMEDICALJOURNAL' : 'BRITISH MEDICAL JOURNAL',
'BMJPUBLISHINGGROUP' : 'BRITISH MEDICAL JOURNAL',
'BMJOPEN' : 'BRITISH MEDICAL JOURNAL',
'STUDENTBMJ' : 'BRITISH MEDICAL JOURNAL',
'BMJBRITISHMEDICALJOURNALINTERNATIONALEDITION' : 'BRITISH MEDICAL JOURNAL',
'BMJCAREERS' : 'BRITISH MEDICAL JOURNAL',
'BMJGROUPPODCASTS' : 'BRITISH MEDICAL JOURNAL',


'PHYSICALREVIEWLETTERS' : 'PHYSICAL REVIEW',
'PHYSICALREVB' : 'PHYSICAL REVIEW',
'PHYSICALREVIEWA' : 'PHYSICAL REVIEW',
'PHYSICALREVIEWB' : 'PHYSICAL REVIEW',
'PHYSICALREVIEWC' : 'PHYSICAL REVIEW',
'PHYSICALREVIEWD' : 'PHYSICAL REVIEW',
'PHYSICALREVIEWDD' : 'PHYSICAL REVIEW',
'PHYSICALREVIEWE' : 'PHYSICAL REVIEW',
'PHYSICALREVIEWESTATISTICALNONLINEARANDSOFTMATTERPHYSICS' : 'PHYSICAL REVIEW',
'PHYSREVLETT' : 'PHYSICAL REVIEW',

'THEASTROPHYSICALJOURNAL' : 'THE ASTROPHYSICAL JOURNAL',
'ASTROPHYSICALJOURNAL' : 'THE ASTROPHYSICAL JOURNAL',
'ASTROPHYSICALJOURNALLETTERS' : 'THE ASTROPHYSICAL JOURNAL',

'JAMA' : 'JOURNAL OF THE AMERICAN MEDICAL ASSOCIATION',
'THEJOURNALOFTHEAMERICANMEDICALASSOCIATION ' : 'JOURNAL OF THE AMERICAN MEDICAL ASSOCIATION',
'JOURNALOFTHEAMERICANMEDICALASSOCIATION' : 'JOURNAL OF THE AMERICAN MEDICAL ASSOCIATION',

'JOURNALOFPERSONALITYANDSOCIALPSYCHOLOGY' : 'JOURNAL OF PERSONALITY AND SOCIAL PSYCHOLOGY',
'PERSONALITYANDSOCIALPSYCHOLOGYREVIEW' : 'JOURNAL OF PERSONALITY AND SOCIAL PSYCHOLOGY',
'BIOCHEMISTRY' : 'BIOCHEMISTRY',

'JOURNALOFVERTEBRATEPALEONTOLOGY' : 'JOURNAL OF VERTEBRATE PALEIONTOLOGY',
'JOURNALOFVERTEBRAEPALEONTOLOGY' : 'JOURNAL OF VERTEBRATE PALEIONTOLOGY',


'NUCLEICACIDSRES' : 'NUCLEIC ACIDS RESEARCH',
'NUCLEICACIDSRESEARCH' : 'NUCLEIC ACIDS RESEARCH',

'JBACTERIOL' : 'JOURNAL OF BACTERIOLOGY',
'JBACTERIOLOGY': 'JOURNAL OF BACTERIOLOGY',
'THEJOURNALOFBACTERIOLOGY' : 'JOURNAL OF BACTERIOLOGY',
'JOURNALOFBACTERIOLOGY' : 'JOURNAL OF BACTERIOLOGY',

'COCHRANEDATABASESYSTREV' : 'COCHRANE DATABASE OF SYSTEMATIC REVIEWS',
'THECOCHRANEDATABASEOFSYSTEMATICREVIEWS' : 'COCHRANE DATABASE OF SYSTEMATIC REVIEWS',
'COCHRANEDATABASEOFSYSTEMATICREVIEWS' : 'COCHRANE DATABASE OF SYSTEMATIC REVIEWS',
'COCHRANEDATABASEOFSYSTEMATICREVIEWSONLINE' : 'COCHRANE DATABASE OF SYSTEMATIC REVIEWS'

}

for letter in 'ABCDEFGHIJKLMNOPQRSTUVWXYQ':
    path = 'http://www.efm.leeds.ac.uk/~mark/ISIabbr/%s_abrvjt.html' % (letter)
    rawlines = urllib.urlopen(path).readlines()
    
    while rawlines:
        line = rawlines.pop(0)
        if '<DT>' in line:
            
            journal_name = line.strip()[line.index('<DT>')+4:]
            line2 = rawlines.pop(0)
            assert '<DD>' in line2
            journal_abbr = line2.strip()[line2.index('<DD>')+4+1:] # the 1 is for '\t'
            journal_abbr_edit = re.sub(r'[^0-9a-zA-Z\s]', u'', journal_abbr, flags=0).replace(" ","")
            #journal_abbr_edit = re.sub(r'[\W_]', u'', journal_abbr, flags=0).replace(" ","")
            #print journal_abbr_edit
            dict_of_journals[journal_abbr_edit] = journal_name

years= defaultdict(int)
journals= defaultdict(int)
journals_years= defaultdict(int)

with open("pagetitle_journal.txt") as infile:
    for line in infile:
        
        line_split= line.split(":")
        if line_split:
            page= line_split[0]
            if not page:
                page= ""
            
            journal = re.search(r'(?<=journal =)[^\|]+', line)
            if not journal:
                journal = re.search(r'(?<=journal=)[^\|]+', line)
            if not journal:
                journal = re.search(r'(?<=work=)[^\|]+', line)
            if not journal:
                journal = re.search(r'(?<=work =)[^\|]+', line)
            if not journal:
                journal = re.search(r'(?<=publisher=)[^\|]+', line)
            if not journal:
                journal = re.search(r'(?<=publisher =)[^\|]+', line)

            if journal:
                journal = journal.group(0)
                journal = re.sub(r'[^0-9a-zA-Z\s]', u'', journal, flags=0).lstrip().rstrip().upper()
                journal_edit = re.sub(r'[^0-9a-zA-Z\s]', u'', journal, flags=0).replace(" ","")

#journal = re.sub(r'[\W_]', u'', journal, flags=0).lstrip().rstrip().upper()
#journal_edit = re.sub(r'[\W_]', u'', journal, flags=0).replace(" ","")

                if journal_edit in dict_of_journals.keys():
                    journal = dict_of_journals[journal_edit]

                journals[journal] = journals[journal] + 1

                year = re.search(r'(?<=year=)[^\|]+', line)
                if not year:
                    year = re.search(r'(?<=year =)[^\|]+', line)
                if year:
                    year= year.group(0).lstrip().rstrip()[:4]
                if not year:
                    year= re.search(r'(?<=date=)[^\|]+', line)
                    if not year:
                        year= re.search(r'(?<=date =)[^\|]+', line)
                    if year:
                        ayear=re.search(r'\d{4}-\d{2}-\d{2}', year.group(0).lstrip().rstrip())
                        if ayear:
                            year= ayear.group(0)[:4] #year.group(0).lstrip().rstrip()[4:]
                        else:
                            year= year.group(0).lstrip().rstrip()[-4:]

                if year:
                    years[year] = years[year] + 1

# if year and journal:
            try:
                journals_years[journal + "," + year]= journals_years[journal + "," + year]+1
            except:
                pass

for key,value in journals_years.items():
    print key, ",", value

#print journal_edit +" : "+dict_of_journals[journal_edit]
#print journal + "."


"""
for key,value in dict_of_journals.items():
    print key, ",", value
"""